server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /olympussnap/ {
        rewrite ^/olympussnap/(.*)$ /$1 last;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
